In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
period_df=pd.read_csv("Period.csv")
symptm_df=pd.read_csv("Symptom.csv")
user_df=pd.read_csv("User.csv")
print(period_df.head(5))
print(50*"=")
print(symptm_df.head(5))
print(50*"=")
print(user_df.head(5))

    id start_date end_date  User_id
0  352     5/4/15  10/4/15      252
1  353    23/3/15  27/3/15      253
2  354     6/4/15  11/4/15      254
3  355    21/3/15  24/3/15      255
4  356    26/3/15  31/3/15      256
==================================================
    id  user_id  acne  backache  bloating  cramp  diarrhea  dizzy  headache  \
0  127      252     0         0         0      0         0      0         0
1  128      257     0         0         0     46         0      0         0
2  129      257     0         0         0      0         0     27        48
3  130      263     0         0         0      0         0      0         0
4  132      269     0         0         0      0         0      0         0

   mood  nausea  sore     date
0     0       0     0  11/4/15
1     0       0     0  10/4/15
2     0       0     0  11/4/15
3     0       0     0  11/4/15
4     0       0     0  11/4/15
==================================================
    id  dob  cycle_length_initial  period_length_initial
0  252  NaN                    28                      6
1  253  NaN                    30                      5
2  254  NaN                    28                      6
3  255  NaN                    30                      4
4  256  NaN                    25                      6

### EDA on Periods data

In [3]:
period_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34942 entries, 0 to 34941
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          34942 non-null  int64
 1   start_date  34939 non-null  object
 2   end_date    32168 non-null  object
 3   User_id     34942 non-null  int64
dtypes: int64(2), object(2)
memory usage: 1.1+ MB

In [4]:
period_df.isnull().sum()

id               0
start_date       3
end_date      2774
User_id          0
dtype: int64

In [5]:
period_df[period_df['start_date'].isnull()]

        id start_date end_date  User_id
4264  5419        NaN      NaN     2233
4265  5420        NaN      NaN     2233
4266  5421        NaN      NaN     2233

In [6]:
period_df=period_df.dropna(subset=['start_date'])
period_df.isnull().sum()

id               0
start_date       0
end_date      2771
User_id          0
dtype: int64

In [7]:
period_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 34939 entries, 0 to 34941
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          34939 non-null  int64
 1   start_date  34939 non-null  object
 2   end_date    32168 non-null  object
 3   User_id     34939 non-null  int64
dtypes: int64(2), object(2)
memory usage: 1.3+ MB

In [8]:
period_df[period_df['end_date'].isnull()]

          id start_date end_date  User_id
17       369    11/4/15      NaN      266
22       375    11/4/15      NaN      271
31       384    12/4/15      NaN      278
36       389    12/4/15      NaN      282
50       410    14/4/15      NaN      297
...      ...        ...      ...      ...
34936  38804    21/3/19      NaN     5545
34937  38805    22/3/19      NaN     4592
34938  38806    21/3/19      NaN      843
34939  38807    22/3/19      NaN     3279
34941  38809    20/3/19      NaN     6305

[2771 rows x 4 columns]

In [9]:
period_df['start_date']=pd.to_datetime(period_df['start_date'])
period_df.info()

/var/folders/1p/j0f7xvr91cgdwsyvj_1fs0q80000gn/T/ipykernel_4845/723938280.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  period_df['start_date']=pd.to_datetime(period_df['start_date'])

OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 0015-03-15, at position 22

In [10]:
period_df['start_date'][period_df['start_date'].str.startswith("00")]

29       0015-03-15
122      0015-04-15
127      0015-04-12
2077     0027-11-05
27038    0030-04-22
Name: start_date, dtype: object

In [11]:
period_df['start_date']=period_df['start_date'].str.replace(r'^00','',regex=True)

In [12]:
period_df['start_date'][period_df['start_date'].str.startswith("00")]

Series([], Name: start_date, dtype: object)

In [13]:
period_df['start_date']=pd.to_datetime(period_df['start_date'])
period_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 34939 entries, 0 to 34941
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          34939 non-null  int64
 1   start_date  34939 non-null  datetime64[ns]
 2   end_date    32168 non-null  object
 3   User_id     34939 non-null  int64
dtypes: datetime64[ns](1), int64(2), object(1)
memory usage: 1.3+ MB

/var/folders/1p/j0f7xvr91cgdwsyvj_1fs0q80000gn/T/ipykernel_4845/723938280.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  period_df['start_date']=pd.to_datetime(period_df['start_date'])

In [14]:
pd.to_datetime(period_df['end_date'])

/var/folders/1p/j0f7xvr91cgdwsyvj_1fs0q80000gn/T/ipykernel_4845/767129850.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(period_df['end_date'])

OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 0015-03-18, at position 20

In [19]:
period_df['end_date'].isnull().sum()

np.int64(2771)

In [23]:
period_df['end_date']=period_df['end_date'].str.replace(r'^00','',regex=True)

In [27]:
period_df['end_date'] = pd.to_datetime(period_df['end_date'], errors='coerce')

/var/folders/1p/j0f7xvr91cgdwsyvj_1fs0q80000gn/T/ipykernel_4845/3316877125.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  period_df['end_date'] = pd.to_datetime(period_df['end_date'], errors='coerce')

In [28]:
period_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 34939 entries, 0 to 34941
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          34939 non-null  int64
 1   start_date  34939 non-null  datetime64[ns]
 2   end_date    32168 non-null  datetime64[ns]
 3   User_id     34939 non-null  int64
dtypes: datetime64[ns](2), int64(2)
memory usage: 1.3 MB

In [ ]:
period_df.isnull().sum()

id               0
start_date       0
end_date      2771
User_id          0
dtype: int64

In [32]:
period_df['end_date']=period_df['end_date'].fillna(period_df['start_date']+pd.Timedelta(days=5))

In [36]:
period_df.isnull().sum()

id            0
start_date    0
end_date      0
User_id       0
dtype: int64

In [38]:
period_df[period_df['id']==369]

     id start_date   end_date  User_id
17  369 2015-11-04 2015-11-09      266

In [39]:
period_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 34939 entries, 0 to 34941
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          34939 non-null  int64
 1   start_date  34939 non-null  datetime64[ns]
 2   end_date    34939 non-null  datetime64[ns]
 3   User_id     34939 non-null  int64
dtypes: datetime64[ns](2), int64(2)
memory usage: 1.3 MB

### EDA on User data

In [41]:
user_df.head(10)

    id  dob  cycle_length_initial  period_length_initial
0  252  NaN                    28                      6
1  253  NaN                    30                      5
2  254  NaN                    28                      6
3  255  NaN                    30                      4
4  256  NaN                    25                      6
5  257  NaN                    30                      6
6  258  NaN                    28                      5
7  259  NaN                    30                      6
8  260  NaN                    28                      6
9  261  NaN                    28                      5

In [42]:
user_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6729 entries, 0 to 6728
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     6729 non-null   int64
 1   dob                    440 non-null    object
 2   cycle_length_initial   6729 non-null   int64
 3   period_length_initial  6729 non-null   int64
dtypes: int64(3), object(1)
memory usage: 210.4+ KB

In [43]:
user_df.isnull().sum()

id                          0
dob                      6289
cycle_length_initial        0
period_length_initial       0
dtype: int64